# Generated by Django 5.0.6 on 2024-05-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_playlist_tube_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tube',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tube',
            field=models.ManyToManyField(to='main_app.tube'),
        ),
    ]
