# Generated by Django 5.0.6 on 2024-05-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_tube_playlist_playlist_tube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='tube',
            new_name='tubes',
        ),
    ]
