# Generated by Django 5.0.6 on 2024-05-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_playlist_users_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='posX',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='playlist',
            name='posY',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='tube',
            name='posX',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='tube',
            name='posY',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='tube',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tube',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
