# Generated by Django 5.0.6 on 2024-08-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_tube_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='posX',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='posY',
        ),
    ]
